version: '3.7'

networks:
  mattermost:

volumes:
  mmst_db: {}
  mmst_data: {}
  mmst_config: {}
  mmst_logs: {}
  mmst_plugins: {}
  mmst_client_plugins: {}
  mmst_nginx: {}

networks:
  mattermost:

services:
  nginx:
    image: nginx
    restart: unless-stopped
    networks:
      - mattermost
    volumes:
      - /vagrant/docker/nginx/templates:/etc/nginx/templates
      - /vagrant/docker/nginx/ssl:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: ${MM_SERVER_NAME}
      NGINX_PORT: 80

  postgres:
    image: postgres
    restart: unless-stopped
    networks:
      - mattermost
    volumes:
      - mmst_db:/var/lib/postgresql/data
    networks:
      - mattermost
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: ${MM_DB_USER}
      POSTGRES_PASSWORD: ${MM_DB_PASSWORD}
      POSTGRES_DB: ${MM_DB_NAME}

  mattermost:
    image: mattermost/mattermost-${MM_EDITION}-edition:${MM_SERVER_VERSION}
    depends_on:
      - "postgres"
      - "nginx"
    restart: unless-stopped
    ports:
      - 8067:8067 # Optional Prometheus monitoring port
    networks:
      - mattermost
    volumes:
      - mmst_data:/mattermost/data # Where file uploads and user avatars are stored
      - mmst_config:/mattermost/config # The config directory, not really used since config is in the database
      - mmst_logs:/mattermost/logs # Logs
      - mmst_plugins:/mattermost/plugins # Server-side plugin components are stored here
      - mmst_client_plugins:/mattermost/client/plugins # Client-side plugin components are stored here
    environment:
      # Use environment variables to set configuration: https://docs.mattermost.com/administration/config-settings.html#environment-variables
      MM_CONFIG: "postgres://${MM_DB_USER}:${MM_DB_PASSWORD}@${MM_DB_HOST}:${MM_DB_PORT}/${MM_DB_NAME}?sslmode=disable&connect_timeout=10"
      MM_SQL_SETTINGS_DATA_SOURCE: "postgres://mmuser:${MM_DB_PASSWORD}@${MM_DB_HOST}:${MM_DB_PORT}/${MM_DB_NAME}?sslmode=disable&connect_timeout=10"